### ISSUE TITLE
Disable "ClearFocusOnPress" on component buttons so keyboard stays open

### ISSUE THREAD

**Issue by 5H4D0W-X** [RileyGuy/CherryPick#4]
Having to click the input field every time can get annoying when adding multiple components at a time. Might be a good idea to make this a config option as well in case some people expect the keyboard to close

**Comment by RileyGuy** [comment]
I can make this a configuration option, but it'll be off by default to be consistent with most other text fields in the game.

**Comment by 5H4D0W-X** [comment]
makes sense

**Comment by RileyGuy** [comment]
Added in version 1.0.3
